export const LOAD_APP_VERSION = 'LOAD_APP_VERSION';

export const LOGIN_DATA = 'LOGIN_DATA';
export const LOGIN_DATA_SUCCESS = 'LOGIN_DATA_SUCCESS';
export const LOGIN_DATA_FAIL = 'LOGIN_DATA_FAIL';
export const LOGIN_DATA_CLEAR = 'LOGIN_DATA_CLEAR';

export const REGISTER_DATA = 'REGISTER_DATA';
export const REGISTER_DATA_SUCCESS = 'REGISTER_DATA_SUCCESS';
export const REGISTER_DATA_FAIL = 'REGISTER_DATA_FAIL';
export const REGISTER_DATA_CLEAR = 'REGISTER_DATA_CLEAR';

export const SEND_OTP = 'SEND_OTP';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';
export const SEND_OTP_CLEAR = 'SEND_OTP_CLEAR';

export const LOGOUT_DATA = 'LOGOUT_DATA';

export const LOAD_PRIVACY_DATA = 'LOAD_PRIVACY_DATA';
export const LOAD_ABOUTUS_DATA = 'LOAD_ABOUTUS_DATA';
export const LOAD_CONTACTUS_DATA = 'LOAD_CONTACTUS_DATA';

export const GET_BLOG_DATA = 'GET_BLOG_DATA';
export const BLOG_DATA_SUCCESS = 'BLOG_DATA_SUCCESS';
export const BLOG_DATA_FAIL = 'BLOG_DATA_FAIL';
export const BLOG_DATA_CLEAR = 'BLOG_DATA_CLEAR';

export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const PROFILE_DATA_SUCCESS = 'PROFILE_DATA_SUCCESS';
export const PROFILE_DATA_FAIL = 'PROFILE_DATA_FAIL';
export const CLEAR_PROFILE_DATA = 'CLEAR_PROFILE_DATA';

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const CLEAR_UPDATE_PROFILE_DATA = 'CLEAR_UPDATE_PROFILE_DATA';

export const GET_QUIZ_DATA = 'GET_QUIZ_DATA';
export const QUIZ_DATA_SUCCESS = 'QUIZ_DATA_SUCCESS';
export const QUIZ_DATA_FAIL = 'QUIZ_DATA_FAIL';
export const QUIZ_DATA_CLEAR = 'QUIZ_DATA_CLEAR';

export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const NOTIFICATION_DATA_SUCCESS = 'NOTIFICATION_DATA_SUCCESS';
export const NOTIFICATION_FAIL = 'NOTIFICATION_FAIL';
export const CLEAR_NOTIFICATION_DATA = 'CLEAR_NOTIFICATION_DATA';

export const GET_SAVE_ANSWER = 'GET_SAVE_ANSWER';
export const SAVE_ANSWER_SUCCESS = 'SAVE_ANSWER_DATA';
export const SAVE_ANSWER_FAIL = 'SAVE_ANSWER_FAIL';
export const CLEAR_ANSWER_DATA = 'CLEAR_ANSWER_DATA';

export const GET_FORGOT_PASSWORD = 'GET_FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const CLEAR_FORGOT_PASSWORD = 'CLEAR_FORGOT_PASSWORD';

export const GET_F_PASSWORD = 'GET_F_PASSWORD';
export const F_PASSWORD_SUCCESS = 'F_PASSWORD_SUCCESS';
export const F_PASSWORD_FAIL = 'F_PASSWORD_FAIL';
export const CLEAR_F_PASSWORD = 'CLEAR_F_PASSWORD';

export const LOAD_SCORE_DATA = 'LOAD_SCORE_DATA';
